// Generated by tools/build-stats.mjs from the Fextralife wiki - do not edit by hand.
var RWA_STATS = {
 "generated": "2026-10-04",
 "weapons": {
  "Repeater Pistol": {
   "name": "Repeater Pistol",
   "type": "Hand Gun",
   "mod": "",
   "damage": 17,
   "damageNote": "",
   "rps": 7,
   "magazine": 15,
   "range": 18,
   "maxAmmo": 120,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Magnum Revolver": {
   "name": "Magnum Revolver",
   "type": "Hand Gun",
   "mod": "",
   "damage": 65,
   "damageNote": "",
   "rps": 1.4,
   "magazine": 6,
   "range": 18,
   "maxAmmo": 30,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Defiler": {
   "name": "Defiler",
   "type": "Hand Gun",
   "mod": "Radioactive Volley",
   "damage": 52,
   "damageNote": "",
   "rps": 2,
   "magazine": 6,
   "range": 13,
   "maxAmmo": 36,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Hunting Pistol": {
   "name": "Hunting Pistol",
   "type": "Hand Gun",
   "mod": "",
   "damage": 105,
   "damageNote": "",
   "rps": 1,
   "magazine": 1,
   "range": 22,
   "maxAmmo": 19,
   "crit": 15,
   "weakspot": 120,
   "special": ""
  },
  "Submachine Gun": {
   "name": "Submachine Gun",
   "type": "Hand Gun",
   "mod": "",
   "damage": 7,
   "damageNote": "",
   "rps": 16,
   "magazine": 40,
   "range": 13,
   "maxAmmo": 280,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Hive Cannon": {
   "name": "Hive Cannon",
   "type": "Hand Gun",
   "mod": "Hive Shot",
   "damage": 57,
   "damageNote": "",
   "rps": 1.8,
   "magazine": 5,
   "range": 16,
   "maxAmmo": 25,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Spitfire": {
   "name": "Spitfire",
   "type": "Hand Gun",
   "mod": "Flame Thrower",
   "damage": 12,
   "damageNote": "",
   "rps": 9.3,
   "magazine": 26,
   "range": 15,
   "maxAmmo": 156,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Curse of the Jungle God": {
   "name": "Curse of the Jungle God",
   "type": "Hand Gun",
   "mod": "Tentacle Shot",
   "damage": 25,
   "damageNote": "",
   "rps": 4,
   "magazine": 18,
   "range": 18,
   "maxAmmo": 72,
   "crit": 10,
   "weakspot": 100,
   "special": ""
  },
  "Pride of the Iskal": {
   "name": "Pride of the Iskal",
   "type": "Hand Gun",
   "mod": "Vampiric",
   "damage": 33,
   "damageNote": "11 + 22",
   "rps": 3.9,
   "magazine": 18,
   "range": 20,
   "maxAmmo": 90,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Machine Pistol": {
   "name": "Machine Pistol",
   "type": "Hand Gun",
   "mod": "",
   "damage": 8,
   "damageNote": "",
   "rps": 18,
   "magazine": 24,
   "range": 18,
   "maxAmmo": 240,
   "crit": 5,
   "weakspot": 75,
   "special": ""
  },
  "Sawed-Off": {
   "name": "Sawed-Off",
   "type": "Hand Gun",
   "mod": "",
   "damage": 125,
   "damageNote": "",
   "rps": 3.5,
   "magazine": 3,
   "range": 5,
   "maxAmmo": 21,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Twin Shot": {
   "name": "Twin Shot",
   "type": "Hand Gun",
   "mod": "",
   "damage": 60,
   "damageNote": "",
   "rps": 7.5,
   "magazine": 2,
   "range": 16,
   "maxAmmo": 34,
   "crit": 15,
   "weakspot": 100,
   "special": ""
  },
  "Hunting Rifle": {
   "name": "Hunting Rifle",
   "type": "Long Gun",
   "mod": "",
   "damage": 55,
   "damageNote": "",
   "rps": 1.9,
   "magazine": 10,
   "range": 25,
   "maxAmmo": 50,
   "crit": 10,
   "weakspot": 110,
   "special": ""
  },
  "Coach Gun": {
   "name": "Coach Gun",
   "type": "Long Gun",
   "mod": "",
   "damage": 102,
   "damageNote": "",
   "rps": 2.5,
   "magazine": 2,
   "range": 9,
   "maxAmmo": 30,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Shotgun": {
   "name": "Shotgun",
   "type": "Long Gun",
   "mod": "",
   "damage": 130,
   "damageNote": "",
   "rps": 0.6,
   "magazine": 7,
   "range": 7,
   "maxAmmo": 25,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Assault Rifle": {
   "name": "Assault Rifle",
   "type": "Long Gun",
   "mod": "",
   "damage": 15,
   "damageNote": "",
   "rps": 7.3,
   "magazine": 32,
   "range": 18,
   "maxAmmo": 224,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Beam Rifle": {
   "name": "Beam Rifle",
   "type": "Long Gun",
   "mod": "",
   "damage": 20,
   "damageNote": "",
   "rps": 4,
   "magazine": 50,
   "range": 15,
   "maxAmmo": 200,
   "crit": 5,
   "weakspot": 75,
   "special": ""
  },
  "Devastator": {
   "name": "Devastator",
   "type": "Long Gun",
   "mod": "Skewer",
   "damage": 175,
   "damageNote": "5 pellets of 35",
   "rps": 2.5,
   "magazine": 1,
   "range": 20,
   "maxAmmo": 30,
   "crit": 10,
   "weakspot": 100,
   "special": ""
  },
  "Sniper Rifle": {
   "name": "Sniper Rifle",
   "type": "Long Gun",
   "mod": "",
   "damage": 125,
   "damageNote": "",
   "rps": 2,
   "magazine": 1,
   "range": 35,
   "maxAmmo": 27,
   "crit": 20,
   "weakspot": 120,
   "special": ""
  },
  "Sporebloom": {
   "name": "Sporebloom",
   "type": "Long Gun",
   "mod": "Spore Shot",
   "damage": 200,
   "damageNote": "",
   "rps": 3.5,
   "magazine": 1,
   "range": 10,
   "maxAmmo": 21,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Crossbow": {
   "name": "Crossbow",
   "type": "Long Gun",
   "mod": "",
   "damage": 115,
   "damageNote": "",
   "rps": 3,
   "magazine": 1,
   "range": 18,
   "maxAmmo": 25,
   "crit": 20,
   "weakspot": 110,
   "special": ""
  },
  "Ruin": {
   "name": "Ruin",
   "type": "Long Gun",
   "mod": "Undying",
   "damage": 19,
   "damageNote": "",
   "rps": 6,
   "magazine": 30,
   "range": 22,
   "maxAmmo": 150,
   "crit": 10,
   "weakspot": 100,
   "special": ""
  },
  "Eye of the Storm": {
   "name": "Eye of the Storm",
   "type": "Long Gun",
   "mod": "Static Field Shot",
   "damage": 65,
   "damageNote": "",
   "rps": 1.7,
   "magazine": 15,
   "range": 25,
   "maxAmmo": 45,
   "crit": 10,
   "weakspot": 110,
   "special": ""
  },
  "Particle Accelerator": {
   "name": "Particle Accelerator",
   "type": "Long Gun",
   "mod": "Gravity Core",
   "damage": 70,
   "damageNote": "",
   "rps": 1.4,
   "magazine": 5,
   "range": 30,
   "maxAmmo": 35,
   "crit": 15,
   "weakspot": 100,
   "special": ""
  },
  "Repulsor": {
   "name": "Repulsor",
   "type": "Long Gun",
   "mod": "Banish",
   "damage": 100,
   "damageNote": "",
   "rps": 1.8,
   "magazine": 5,
   "range": 8,
   "maxAmmo": 30,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Chicago Typewriter": {
   "name": "Chicago Typewriter",
   "type": "Long Gun",
   "mod": "",
   "damage": 11,
   "damageNote": "",
   "rps": 8.8,
   "magazine": 80,
   "range": 15,
   "maxAmmo": 320,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Ricochet Rifle": {
   "name": "Ricochet Rifle",
   "type": "Long Gun",
   "mod": "",
   "damage": 80,
   "damageNote": "",
   "rps": 2,
   "magazine": 1,
   "range": 20,
   "maxAmmo": 22,
   "crit": 5,
   "weakspot": 120,
   "special": ""
  },
  "Alternator": {
   "name": "Alternator",
   "type": "Long Gun",
   "mod": "Incinerator",
   "damage": 14,
   "damageNote": "",
   "rps": 9,
   "magazine": 32,
   "range": 17,
   "maxAmmo": 224,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Fusion Rifle": {
   "name": "Fusion Rifle",
   "type": "Long Gun",
   "mod": "Fusion Cannon",
   "damage": 9,
   "damageNote": "",
   "rps": 2.8,
   "magazine": 50,
   "range": 20,
   "maxAmmo": 300,
   "crit": 5,
   "weakspot": 100,
   "special": ""
  },
  "Scrap Sword": {
   "name": "Scrap Sword",
   "type": "Melee",
   "mod": "",
   "damage": 52,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "N/A"
  },
  "Scrap Hammer": {
   "name": "Scrap Hammer",
   "type": "Melee",
   "mod": "",
   "damage": 78,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "N/A"
  },
  "Scrap Hatchet": {
   "name": "Scrap Hatchet",
   "type": "Melee",
   "mod": "",
   "damage": 60,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "N/A"
  },
  "Blade of Adventure": {
   "name": "Blade of Adventure",
   "type": "Melee",
   "mod": "",
   "damage": 26,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 0,
   "weakspot": 10,
   "special": "N/A"
  },
  "Petrified Maul": {
   "name": "Petrified Maul",
   "type": "Melee",
   "mod": "",
   "damage": 75,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Heavy Impact   Charge attacks have a 100% chance to inflict bonus stagger damage."
  },
  "Wastelander Flail": {
   "name": "Wastelander Flail",
   "type": "Melee",
   "mod": "",
   "damage": 62,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "N/A"
  },
  "Scythe": {
   "name": "Scythe",
   "type": "Melee",
   "mod": "",
   "damage": 47,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 15,
   "weakspot": 10,
   "special": "N/A"
  },
  "World Breaker": {
   "name": "World Breaker",
   "type": "Melee",
   "mod": "",
   "damage": 68,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Force Burst   Charge attacks release an explosive force that will stagger and push enemies back"
  },
  "Riven": {
   "name": "Riven",
   "type": "Melee",
   "mod": "",
   "damage": 37,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 15,
   "weakspot": 10,
   "special": "Life Steal   Melee hits steal 4% of the base damage dealt as Health"
  },
  "Spear": {
   "name": "Spear",
   "type": "Melee",
   "mod": "",
   "damage": 50,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "N/A"
  },
  "Scar of the Jungle God": {
   "name": "Scar of the Jungle God",
   "type": "Melee",
   "mod": "",
   "damage": 27,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Razor Sharp   Charge attacks have apply the BLEEDING effect dealing 200 damage over 20 seconds"
  },
  "Smolder": {
   "name": "Smolder",
   "type": "Melee",
   "mod": "",
   "damage": 45,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "Blaze    Charge attacks apply the BURNING effect which will deal 100 fire damage over 10 seconds."
  },
  "Voice of the Tempest": {
   "name": "Voice of the Tempest",
   "type": "Melee",
   "mod": "",
   "damage": 47,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "Lightning Shock   Charge attacks apply the OVERLOADED effect."
  },
  "Butcher's Flail": {
   "name": "Butcher's Flail",
   "type": "Melee",
   "mod": "",
   "damage": 60,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Corrosive Strike   Strikes apply CORRODED stack. Each stack reduces enemy defense by 5%. Max 5 stack. Last 10 seconds. Charged attacks apply 2 stacks."
  },
  "Guardian Axe": {
   "name": "Guardian Axe",
   "type": "Melee",
   "mod": "",
   "damage": 51,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Spirit Engine   Generates 2x the amount of Mod Power per damage dealt."
  },
  "Lost Harpoon": {
   "name": "Lost Harpoon",
   "type": "Melee",
   "mod": "",
   "damage": 39,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "Power Strike   Increases damage on each successive hit by 10% for 15 seconds. Can be stacked 5 times."
  },
  "Hero's Sword": {
   "name": "Hero's Sword",
   "type": "Melee",
   "mod": "",
   "damage": 48,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 0,
   "weakspot": 10,
   "special": "Energy Wave   Charge attacks release an energy wave allowing the wielder to strike enemies from farther away."
  },
  "Chain Blade": {
   "name": "Chain Blade",
   "type": "Melee",
   "mod": "",
   "damage": 47,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Chain Strike   Charge Attacks extend the chain allowing the wielder to hit enemies from farther away"
  },
  "World's Edge": {
   "name": "World's Edge",
   "type": "Melee",
   "mod": "",
   "damage": 45,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 10,
   "weakspot": 10,
   "special": "Horizon Strike   Charge attacks release a wide wave projectile that will penetrate through multiple enemies"
  },
  "Frostborne": {
   "name": "Frostborne",
   "type": "Melee",
   "mod": "",
   "damage": 50,
   "damageNote": "",
   "rps": null,
   "magazine": null,
   "range": null,
   "maxAmmo": null,
   "crit": 5,
   "weakspot": 10,
   "special": "Cold Strike   Strikes apply FROSTBITE stacks. Charge attacks apply 2 stacks per hit"
  }
 },
 "traits": {
  "Arcane Strike": {
   "name": "Arcane Strike",
   "type": "Weapon Mod-Related",
   "effect": "Increases Mod Power generation on Melee hits.",
   "perLevel": "+1.25% Melee Mod Power Generation.",
   "max": "+25% Melee Mod Power Generation."
  },
  "Armor Piercer": {
   "name": "Armor Piercer",
   "type": "Offensive (General)",
   "effect": "Increases damage dealt to enemy armored regions.",
   "perLevel": "+1% Bonus Damage to Armor.",
   "max": "+20% Bonus Damage to Armor."
  },
  "Bark Skin": {
   "name": "Bark Skin",
   "type": "Defensive",
   "effect": "Increases Armor Effectiveness.",
   "perLevel": "+0.75% Armor Effectiveness.",
   "max": "+15% Armor Effectiveness."
  },
  "Blood Bond": {
   "name": "Blood Bond",
   "type": "Weapon Mod-Related",
   "effect": "Increases damage absorbed by Summons when the summoner takes damage.",
   "perLevel": "0.75% Summon Damage Absorption.",
   "max": "15% Summon Damage Absorption."
  },
  "Catalyst": {
   "name": "Catalyst",
   "type": "Weapon Mod-Related",
   "effect": "Increases Mod Power Generation when attacking an enemy with an active Status Effect.",
   "perLevel": "+2% Mod Power Generation on Status-afflicted enemies.",
   "max": "+40% Mod Power Generation on Status-afflicted enemies."
  },
  "Climber": {
   "name": "Climber",
   "type": "Mobility",
   "effect": "Increases Vaulting Speed.",
   "perLevel": "+1% Vaulting Speed.",
   "max": "+20% Vaulting Speed."
  },
  "Cold As Ice": {
   "name": "Cold As Ice",
   "type": "Offensive (General)",
   "effect": "Increases Ranged and Melee damage dealt to enemies when attacking them from behind.",
   "perLevel": "+0.5% Backstab Damage Bonus.",
   "max": "+10% Backstab Damage Bonus."
  },
  "Concentration": {
   "name": "Concentration",
   "type": "Weapon Mod-Related",
   "effect": "Increases Weapon Mod Duration.",
   "perLevel": "+1% Weapon Mod Duration.",
   "max": "+20% Weapon Mod Duration."
  },
  "Demolitionist": {
   "name": "Demolitionist",
   "type": "Offensive (General)",
   "effect": "Increases Explosion damage.",
   "perLevel": "+0.75% Explosion Damage Bonus.",
   "max": "+15% Explosion Damage Bonus."
  },
  "Elder Knowledge": {
   "name": "Elder Knowledge",
   "type": "Misc (Resources)",
   "effect": "Increases Experience earned from killing enemies.",
   "perLevel": "+1% Bonus Experience.",
   "max": "+20% Bonus Experience."
  },
  "Endurance": {
   "name": "Endurance",
   "type": "Core Stats",
   "effect": "Increases Stamina.",
   "perLevel": "+2.5 Stamina",
   "max": "+50 Stamina"
  },
  "Evocation": {
   "name": "Evocation",
   "type": "Weapon Mod-Related",
   "effect": "Increases Weapon Mod damage.",
   "perLevel": "+0.75% Weapon Mod Damage.",
   "max": "+15% Weapon Mod Damage."
  },
  "Executioner": {
   "name": "Executioner",
   "type": "Offensive (General)",
   "effect": "Increases Critical Hit Chance.",
   "perLevel": "+1.25% Critical Hit Chance.",
   "max": "+25% Critical Hit Chance."
  },
  "Exploiter": {
   "name": "Exploiter",
   "type": "Offensive (General)",
   "effect": "Increases Weak Spot damage.",
   "perLevel": "+1% Weak Spot Damage Bonus.",
   "max": "+20% Weak Spot Damage Bonus."
  },
  "Flash Caster": {
   "name": "Flash Caster",
   "type": "Weapon Mod-Related",
   "effect": "Increases Weapon Mod Casting Speed.",
   "perLevel": "+1.25% Weapon Mod Casting Speed.",
   "max": "+25% Weapon Mod Casting Speed."
  },
  "Footwork": {
   "name": "Footwork",
   "type": "Mobility",
   "effect": "Increases Aim Movement Speed.",
   "perLevel": "+1.25% Aiming Movement Speed.",
   "max": "+25% Aiming Movement Speed."
  },
  "Fortification": {
   "name": "Fortification",
   "type": "Misc (Multiplayer)",
   "effect": "Reduces damage taken while reviving.",
   "perLevel": "-1.25% Damage Reduction while reviving.",
   "max": "-25% Damage Reduction while reviving."
  },
  "Glutton": {
   "name": "Glutton",
   "type": "Misc (Resources )",
   "effect": "Increases Consumable Use Speed.",
   "perLevel": "+1.75% Consumable Use Speed.",
   "max": "+35% Consumable Use Speed."
  },
  "Guardian's Blessing": {
   "name": "Guardian's Blessing",
   "type": "Defensive",
   "effect": "Increases Melee Damage Reduction.",
   "perLevel": "+0.5% Melee Damage Reduction.",
   "max": "+10% Melee Damage Reduction."
  },
  "Handling": {
   "name": "Handling",
   "type": "Offensive (Ranged)",
   "effect": "Reduces Weapon Spread and Recoil.",
   "perLevel": "-1% Spread and Recoil.",
   "max": "-20% Spread and Recoil."
  },
  "Hard Charger": {
   "name": "Hard Charger",
   "type": "Offensive (Melee)",
   "effect": "Increases Melee Charge damage.",
   "perLevel": "+1% Melee Charge Damage.",
   "max": "+20% Melee Charge Damage."
  },
  "Invoker": {
   "name": "Invoker",
   "type": "Weapon Mod-Related",
   "effect": "Increases Summon damage.",
   "perLevel": "+1% Summon Damage.",
   "max": "+20% Summon Damage."
  },
  "Keeper's Blessing": {
   "name": "Keeper's Blessing",
   "type": "Defensive",
   "effect": "Increases resistance to Elemental Damage.",
   "perLevel": "+0.5% Elemental Damage Resistance.",
   "max": "+10% Elemental Damage Resistance."
  },
  "Kingslayer": {
   "name": "Kingslayer",
   "type": "Offensive (General)",
   "effect": "Increases Critical Hit damage.",
   "perLevel": "+1.25% Critical Hit Damage Bonus.",
   "max": "+25% Critical Hit Damage Bonus."
  },
  "Last Resort": {
   "name": "Last Resort",
   "type": "Offensive (General)",
   "effect": "Increases all damage dealt when Health is below 15%.",
   "perLevel": "+1% Low Health Damage Bonus",
   "max": "+20% Low Health Damage Bonus"
  },
  "Luminescent": {
   "name": "Luminescent",
   "type": "Misc (Resources)",
   "effect": "Increases chance to double the amount of Lumenite Crystal acquired on pickup when killing Elite enemies.",
   "perLevel": "+1.5% Chance to Double Lumenite Crystal drops.",
   "max": "+30% Chance to Double Lumenite Crystal drops."
  },
  "Mind's Eye": {
   "name": "Mind's Eye",
   "type": "Offensive (Ranged)",
   "effect": "Increases Ranged damage.",
   "perLevel": "+0.75% Ranged Damage Bonus.",
   "max": "+15% Ranged Damage Bonus."
  },
  "Mother's Blessing": {
   "name": "Mother's Blessing",
   "type": "Defensive",
   "effect": "Increases Ranged Damage Reduction.",
   "perLevel": "+0.5% Ranged Damge Reduction.",
   "max": "+10% Ranged Damage Reduction."
  },
  "Potency": {
   "name": "Potency",
   "type": "Misc (Resources)",
   "effect": "Increases Consumable Duration.",
   "perLevel": "+1% Consumable Duration.",
   "max": "+20% Consumable Duration."
  },
  "Quick Hands": {
   "name": "Quick Hands",
   "type": "Offensive (Ranged)",
   "effect": "Increases Reload Speed.",
   "perLevel": "+1.25% Reload Speed.",
   "max": "+25% Reload Speed."
  },
  "Rapid Strike": {
   "name": "Rapid Strike",
   "type": "Offensive (Melee)",
   "effect": "Increases Melee Speed.",
   "perLevel": "+0.75% Melee Attack Speed.",
   "max": "+15% Melee Attack Speed."
  },
  "Recovery": {
   "name": "Recovery",
   "type": "Core Stats",
   "effect": "Increases Stamina Regen.",
   "perLevel": "+1 Stamina Regen per second.",
   "max": "+20 Stamina Regen per second."
  },
  "Revivalist": {
   "name": "Revivalist",
   "type": "Misc (Multiplayer)",
   "effect": "Increases Revive Speed.",
   "perLevel": "+5% Revive Speed.",
   "max": "+100% Revive Speed."
  },
  "Scavenger": {
   "name": "Scavenger",
   "type": "Misc (Resources)",
   "effect": "Increases the amount of Scrap picked up.",
   "perLevel": "+1.75% Scrap Bonus.",
   "max": "+35% Scrap Bonus."
  },
  "Shadow Walker": {
   "name": "Shadow Walker",
   "type": "Defensive",
   "effect": "Reduces Enemy Awareness Range.",
   "perLevel": "-1.5% Enemy Awareness Range.",
   "max": "-30% Enemy Awareness Range."
  },
  "Siphoner": {
   "name": "Siphoner",
   "type": "Offensive (General)",
   "effect": "Increases Life Steal rate.",
   "perLevel": "+1% Life Steal Rate Bonus.",
   "max": "+20% Life Steal Rate Bonus."
  },
  "Sleight of Hand": {
   "name": "Sleight of Hand",
   "type": "Offensive (Ranged)",
   "effect": "Increases Firearm Swap Speed.",
   "perLevel": "+2.5% Firearm Swap Speed.",
   "max": "+50% Firearm Swap Speed."
  },
  "Spirit": {
   "name": "Spirit",
   "type": "Weapon Mod-Related",
   "effect": "Increases Mod Power generation.",
   "perLevel": "+1.25% Mod Power Generation.",
   "max": "+25% Mod Power Generation."
  },
  "Suspicion": {
   "name": "Suspicion",
   "type": "Misc (Multiplayer)",
   "effect": "Reduces damage taken from friendly fire.",
   "perLevel": "-2.5% Friendly Fire Damage Reduction.",
   "max": "-50% Friendly Fire Damage Reduction."
  },
  "Swiftness": {
   "name": "Swiftness",
   "type": "Mobility",
   "effect": "Increases Movement Speed.",
   "perLevel": "+0.75 Movement Speed.",
   "max": "+15% Movement Speed."
  },
  "Teamwork": {
   "name": "Teamwork",
   "type": "Misc (Multiplayer)",
   "effect": "Extends the range of the Teamwork buff.",
   "perLevel": "+1m Teamwork Buff Range.",
   "max": "+20m Teamwork Buff Range."
  },
  "Tormentor": {
   "name": "Tormentor",
   "type": "Offensive (General)",
   "effect": "Increases Status effect duration when applied to enemies.",
   "perLevel": "+1.5% Status Effect Duration.",
   "max": "+30% Status Effect Duration."
  },
  "Triage": {
   "name": "Triage",
   "type": "Core Stats",
   "effect": "Increases Healing Effectiveness.",
   "perLevel": "+5% Healing Effectiveness.",
   "max": "+100% Healing Effectiveness."
  },
  "Trigger Happy": {
   "name": "Trigger Happy",
   "type": "Offensive (Ranged)",
   "effect": "Increases Fire Rate.",
   "perLevel": "+1% Fire Rate.",
   "max": "+20% Fire Rate."
  },
  "Vaccine": {
   "name": "Vaccine",
   "type": "Defensive",
   "effect": "Reduces Status Effect build-up rate.",
   "perLevel": "-1.5% Status Effect Build-up Rate.",
   "max": "-30% Status Effect Build-up Rate."
  },
  "Vigor": {
   "name": "Vigor",
   "type": "Core Stats",
   "effect": "Increases Health.",
   "perLevel": "+2.5 Health",
   "max": "+50 Health"
  },
  "Warrior": {
   "name": "Warrior",
   "type": "Offensive (Melee)",
   "effect": "Increases Melee damage.",
   "perLevel": "+1% Melee Damage.",
   "max": "+20% Melee Damage."
  },
  "Will to Live": {
   "name": "Will to Live",
   "type": "Misc (Multiplayer)",
   "effect": "Increases Health while wounded.",
   "perLevel": "+5% Wounded Health.",
   "max": "+100% Wounded Health."
  },
  "Wisdom": {
   "name": "Wisdom",
   "type": "Offensive (General)",
   "effect": "Increases Elemental damage.",
   "perLevel": "+0.5% Elemental Damage dealt.",
   "max": "+10% Elemental Damage dealt."
  },
  "World Walker": {
   "name": "World Walker",
   "type": "Core Stats",
   "effect": "Reduces Stamina Cost when sprinting and evading.",
   "perLevel": "-1% Stamina Consumption.",
   "max": "-20% Stamina Consumption."
  }
 },
 "rings": {
  "Aggressor's Bane": {
   "name": "Aggressor's Bane",
   "effect": "Reduces incoming damage by 15%, but also increases enemy aggression towards the wearer, and increases enemy awareness by range 200%."
  },
  "Akari War Band": {
   "name": "Akari War Band",
   "effect": "Perfect Dodging enemy attacks increases Crit Chance by 15% and Crit damage by 15% for 20 seconds."
  },
  "Alchemist's Jewel": {
   "name": "Alchemist's Jewel",
   "effect": "Increase Armor Effectiveness by 50%, but also increases Armor Encumbrance by 25."
  },
  "Amber Moonstone": {
   "name": "Amber Moonstone",
   "effect": "When the wearer's Health drops below 25% they gain 25% damage reduction and immunity to STATUS effects."
  },
  "Backbreaker Ring": {
   "name": "Backbreaker Ring",
   "effect": "Increase Melee Backstab damage by 30%."
  },
  "Band of Accord": {
   "name": "Band of Accord",
   "effect": "Ammo acquired on pickup is increased by 25% per ally also wearing this ring and is shared with other allies."
  },
  "Band of Castor": {
   "name": "Band of Castor",
   "effect": "Increases Melee Speed by 10%, but Reduces Fire Rate by 15%. While wearing Band of Pollux, Melee damage is increased by 10%, Evade Speed is increased by 15% and Encumbrance is reduced by 25."
  },
  "Band of Discord": {
   "name": "Band of Discord",
   "effect": "Reduces Consumable Use Speed by 15%. Dragon Hearts heal the wearer with 125 Health over 30 seconds."
  },
  "Band of Pollux": {
   "name": "Band of Pollux",
   "effect": "Increases Melee damage by 15%, but reduces Ranged damage by 15%. While wearing Band of Castor, Melee Damage is increased by 10%, Evade Speed is increased by 15% and Encumbrance is reduced by 25."
  },
  "Band of Strength": {
   "name": "Band of Strength",
   "effect": "Melee Charge Attacks increase Melee damage by 5% for 10 seconds. Stacks up to 4 times."
  },
  "Black Cat Band": {
   "name": "Black Cat Band",
   "effect": "When taking fatal damage, instead of dying, the wearer's Health will drop to 1, and Movement Speed will increase by 25% for 10 seconds. 1 minute cooldown."
  },
  "Blood Font": {
   "name": "Blood Font",
   "effect": "Increases Health regenerates by 0.334 Health per second and increases all Healing Effectiveness by 15%."
  },
  "Bloodletter's Insignia": {
   "name": "Bloodletter's Insignia",
   "effect": "BLEEDING effects applied by the wearer steal 10% of the damage dealt and return it to the wearer as Health."
  },
  "Braided Thorns": {
   "name": "Braided Thorns",
   "effect": "Increase Crit Chance by 10%. Gain an additional 10% for 10 seconds after slaying an enemy."
  },
  "Bright Steel Ring": {
   "name": "Bright Steel Ring",
   "effect": "Gives wearer the fastest evade roll regardless of their Armor Encumbrance."
  },
  "Burden of the Devoted": {
   "name": "Burden of the Devoted",
   "effect": "All damage dealt by wearer is reduced by 15%. 50% of self healing applies to allies."
  },
  "Burden of the Follower": {
   "name": "Burden of the Follower",
   "effect": "Reduces Fire Rate by 35%. Increases Mod Power generation by 100%."
  },
  "Burden of the Gambler": {
   "name": "Burden of the Gambler",
   "effect": "Disables Weakspot damage bonus. Increases Crit Chance by 15% and Crit Damage by 25%."
  },
  "Burden of the Reckless": {
   "name": "Burden of the Reckless",
   "effect": "Disables healing from Dragon hearts. Perfect dodgin enemy attacks will regenerate 5% of the wearer's Max Health per second over 5 seconds."
  },
  "Burden of the Warlord": {
   "name": "Burden of the Warlord",
   "effect": "Reduces the effective range of all firearms by 50%. Increases all damage dealt by 15%."
  },
  "Celerity Stone": {
   "name": "Celerity Stone",
   "effect": "Increases Consumable and Relic Use Speed by 20%"
  },
  "Compulsion Loop": {
   "name": "Compulsion Loop",
   "effect": "Increase Movement Speed by 20%, Fire Rate by 15%, and Melee Speed by 10% for 7 seconds after slaying an enemy."
  },
  "Deceiver's Band": {
   "name": "Deceiver's Band",
   "effect": "Increases Evade Speed by 25% and Movement Speed by 15% for 10 seconds after performing a slide."
  },
  "Devouring Loop": {
   "name": "Devouring Loop",
   "effect": "Critical Hits have a 5% chance to deal 4x damage."
  },
  "Empowering Loop": {
   "name": "Empowering Loop",
   "effect": "Increases Ranged damage by 25%, but decrease Fire rate by 10%"
  },
  "Evoker's Seal": {
   "name": "Evoker's Seal",
   "effect": "Refunds 15% Mod Power on use."
  },
  "Ezlan's Band": {
   "name": "Ezlan's Band",
   "effect": "Increases Health by 25 and Health regeneration by 0.238 per second."
  },
  "Five Fingered Ring": {
   "name": "Five Fingered Ring",
   "effect": "Increases Unarmed Melee damage by 50%, Crit damage by 25%, and Crit Chance by 20%."
  },
  "Gift of the Iskal": {
   "name": "Gift of the Iskal",
   "effect": "Mod power is generated slowly over time, but reduces the wearer's Healing Effectiveness by 15%"
  },
  "Gravity Stone": {
   "name": "Gravity Stone",
   "effect": "Increases damage by 20% when there are at least 2 enemies within 10 meters of the wearer."
  },
  "Grim Coil": {
   "name": "Grim Coil",
   "effect": "Reloading a weapon after dealing at least 40% of the base damage from a single magazine increases damage by 7% for 20 seconds. Stacks 3 times."
  },
  "Guardian's Ring": {
   "name": "Guardian's Ring",
   "effect": "Reduce incoming melee damage by 20%."
  },
  "Gunslinger's Ring": {
   "name": "Gunslinger's Ring",
   "effect": "Increases Firearm Swap Speed by 50% and Fire Rate by 10%"
  },
  "Heart of the Wolf": {
   "name": "Heart of the Wolf",
   "effect": "Increases Max Stamina by 25 and Movement Speed by 10%"
  },
  "Heartseeker": {
   "name": "Heartseeker",
   "effect": "Provides a 100% Crit Chance against non-aggressive enemies and increases Crit Damage by 20%."
  },
  "Hero's Ring": {
   "name": "Hero's Ring",
   "effect": "Increases Movement Speed by 25% while sprinting towards a wounded teammate. Revive Speed is increased by 100% and the wearer cannot be staggered while reviving"
  },
  "Hunter's Band": {
   "name": "Hunter's Band",
   "effect": "Increases Ranged damage by 10% and Weakspot damage by 20%."
  },
  "Hunter's Halo": {
   "name": "Hunter's Halo",
   "effect": "Increase the effective Range of all firearms by 6m"
  },
  "Iskal Hunter Band": {
   "name": "Iskal Hunter Band",
   "effect": "Reduces Spread by 40%"
  },
  "Jewel of the Black Sun": {
   "name": "Jewel of the Black Sun",
   "effect": "Increases Ranged damage by 7% for 20 seconds after a ranged kill. Stacks 3 times."
  },
  "Juggernaut Band": {
   "name": "Juggernaut Band",
   "effect": "After sprinting for 2 seconds, incoming damage is reduced by 10%, Movement Speed is increased by 15%, stagger level is reduced by 1, and the wearer will perform the heaviest evade."
  },
  "Keeper's Ring": {
   "name": "Keeper's Ring",
   "effect": "Increases resistance to all elemental damage by 20."
  },
  "Leech Ember": {
   "name": "Leech Ember",
   "effect": "Melee hits steal 5% damage dealt as Health from enemies."
  },
  "Loop of Prosperity": {
   "name": "Loop of Prosperity",
   "effect": "Metal materials acquired on pickup are doubled"
  },
  "Mother's Ring": {
   "name": "Mother's Ring",
   "effect": "Reduces incoming Ranged Damage by 20%"
  },
  "Pearl of Luminescence": {
   "name": "Pearl of Luminescence",
   "effect": "Wearer has a 70% chance to double the amount of Lumenite Crystal acquired on pickup when killing Elite enemies"
  },
  "Pillar of Stone": {
   "name": "Pillar of Stone",
   "effect": "Reduces Recoil by 30% and Weapon Sway by 60%. Standing Aim Movement Speed is increased by 50%."
  },
  "Prismatic Diamond Ring": {
   "name": "Prismatic Diamond Ring",
   "effect": "Increases ELEMENTAL damage by 10%."
  },
  "Provisioner Ring": {
   "name": "Provisioner Ring",
   "effect": "Firearms reload over time while stowed"
  },
  "Razorstone": {
   "name": "Razorstone",
   "effect": "Melee Charge Attacks apply the BLEEDING effect dealing 600 damage over 20 seconds."
  },
  "Restriction Cord": {
   "name": "Restriction Cord",
   "effect": "Restricts the wearer from Healing above 50% of their Max Health and reduces incoming damage by 15%."
  },
  "Ring of Elusion": {
   "name": "Ring of Elusion",
   "effect": "Perfect Dodging enemy attacks refunds 50 Stamina and reduces Stamina Cost by 100% for 10 seconds"
  },
  "Ring of Evasion": {
   "name": "Ring of Evasion",
   "effect": "Moderately increases Evade Window and increases Evade Speed by 10%."
  },
  "Ring of Flawless Beauty": {
   "name": "Ring of Flawless Beauty",
   "effect": "Ranged Weakspot damage is increased by 40%. Ranged damage is reduced by 20% when failing to shoot a weakspot."
  },
  "Ring of Honor": {
   "name": "Ring of Honor",
   "effect": "Increases Health by 10, Stamina by 10, and reduces Armor Encumbrance by 10."
  },
  "Ring of Shadows": {
   "name": "Ring of Shadows",
   "effect": "Reduces enemy Awareness Range by 25%. Increases damage against non-aggresive enemies by 15%."
  },
  "Ring of Supremacy": {
   "name": "Ring of Supremacy",
   "effect": "Increases all damage dealt by 20% after the wearer's health has been full for at least 10 seconds"
  },
  "Ring of Synergy": {
   "name": "Ring of Synergy",
   "effect": "Increase Teamwork effect by 10% and Revival Speed by 11% per ally also wearing this ring."
  },
  "Ring of the Admiral": {
   "name": "Ring of the Admiral",
   "effect": "Damage received is increased by 200%. All damage dealt is increased by 15%."
  },
  "Ring of the Mantis": {
   "name": "Ring of the Mantis",
   "effect": "Increases Fire Rate by 15% and Crit damage by 20% when the wearer stops moving for at least 1 seconds"
  },
  "Ring of the Punisher": {
   "name": "Ring of the Punisher",
   "effect": "Increases damage to enemies affected by STATUS effects. Each unique STATUS applied increases all damage by 5%."
  },
  "Ring of the Unclean": {
   "name": "Ring of the Unclean",
   "effect": "Unarmed Melee attacks deal 2x damage. Heavy Flops deal 4x damage."
  },
  "Root Circlet": {
   "name": "Root Circlet",
   "effect": "Increases Melee Speed by 15%."
  },
  "Sagestone": {
   "name": "Sagestone",
   "effect": "Increases earned Experience by 30%"
  },
  "Scavenger's Ring": {
   "name": "Scavenger's Ring",
   "effect": "Collecting Scrap, Iron, and Ammo pickups regenerates 3% of Max Health and increases Ranged and Melee damage by 10% for 30 seconds."
  },
  "Serpent's Fang": {
   "name": "Serpent's Fang",
   "effect": "Increased Charged Melee Damage by 20%."
  },
  "Soul Ember": {
   "name": "Soul Ember",
   "effect": "Summon Health is reduced by 60%. On death they'll explode dealing 150 plus 15 damage per weapon level within 4 meters. Summons that explode normally will deal 25% bonus damage."
  },
  "Soul Link": {
   "name": "Soul Link",
   "effect": "Summons will steal 5% of the damage dealt and return it to the wearer as health"
  },
  "Spirit Stone": {
   "name": "Spirit Stone",
   "effect": "Increases Mod Power generation by 25% and Weapon Mod damage by 10%."
  },
  "Stockpile Circlet": {
   "name": "Stockpile Circlet",
   "effect": "Increases Max Ammo reserves for all firearms by 50%"
  },
  "Stone of Balance": {
   "name": "Stone of Balance",
   "effect": "Increases Ranged and Melee damage by 12%"
  },
  "Swashbuckler's Signet": {
   "name": "Swashbuckler's Signet",
   "effect": "Build one buff stack every 20 seconds up to a max of 3 stacks. Melee Charge Attacks consume one stack and replenish 15% of the wearer's ammo capacity for both firearms."
  },
  "Vanguard Ring": {
   "name": "Vanguard Ring",
   "effect": "Melee Charge Attacks reduce incoming and outgoing dmg by 4% and increase enemy aggression towards the wearer for 15s. Stacks 5 times."
  },
  "Volatile Gem": {
   "name": "Volatile Gem",
   "effect": "Dragon Hearts explode dealing 200 base Melee damage inflicting 100% bonus stagger damage to enemies within 5m. Gains 10% bonus damage per Gear Score. (GS0 = 0% , GS20 = 200%)."
  }
 },
 "amulets": {
  "Abrasive Amulet": {
   "name": "Abrasive Amulet",
   "effect": "Doubles application of the CORRODED effect. Melee Charge Attacks apply the CORRODED effect."
  },
  "Amulet of Epicaricacy": {
   "name": "Amulet of Epicaricacy",
   "effect": "Increases Mod Power generation by 15%. When attacking an enemy with an active STATUS EFFECT. Mod power generation is increased by an additional 30%."
  },
  "Black Rose": {
   "name": "Black Rose",
   "effect": "The wearer's chest armor set bonus is increased by 1 piece. It will not exceed the 3 piece armor set bonus."
  },
  "Blessed Necklace": {
   "name": "Blessed Necklace",
   "effect": "Receiving a benefit from a Dragon Heart reduces incoming damage by 30% for 10s."
  },
  "Brutal Mark": {
   "name": "Brutal Mark",
   "effect": "After being equipped for 60 seconds, increases all damage by 25% to enemies that have less than 50% Health."
  },
  "Butcher's Fetish": {
   "name": "Butcher's Fetish",
   "effect": "Gain 15% Crit Chance and 25% Crit Damage for 10 seconds after striking and enemy with a Charge Melee Attack."
  },
  "Charcoal Necklace": {
   "name": "Charcoal Necklace",
   "effect": "Increase FIRE damage from all sources by 15% and BURNING damage by 50%."
  },
  "Cleansing Jewel": {
   "name": "Cleansing Jewel",
   "effect": "Dragon Heart removes all STATUS effects from all allies. STATUS effect buildup on wearer is reduced by 50%."
  },
  "Daredevil's Charm": {
   "name": "Daredevil's Charm",
   "effect": "Increases Total damage dealt by 30% for each piece of unequipped armor. Damage received is increased by 15%."
  },
  "Driftstone": {
   "name": "Driftstone",
   "effect": "Doubles FROSTBITE application s."
  },
  "Galenic Charm": {
   "name": "Galenic Charm",
   "effect": "Increases Weapon Mod damage by 25%."
  },
  "Gunslinger's Charm": {
   "name": "Gunslinger's Charm",
   "effect": "Increases Fire Rate by 15% and Reload Speed by 20%."
  },
  "Hangman's Memento": {
   "name": "Hangman's Memento",
   "effect": "Increase Weakspot damage by an additional 50% for 10 seconds after killing an enemy."
  },
  "Heart of Darkness": {
   "name": "Heart of Darkness",
   "effect": "Increases Ranged and Melee damage dealt by 20%. Increases damage received by 50% for 30 seconds after using a Dragon Heart."
  },
  "Leto's Amulet": {
   "name": "Leto's Amulet",
   "effect": "Reduces Armor Encumbrance by 40% and Stamina cost by 15%."
  },
  "Mender's Charm": {
   "name": "Mender's Charm",
   "effect": "Dragon Hearts heal all allies with 100% base effectiveness. Increases all Healing Effectiveness by 50%."
  },
  "Nightmare Spiral": {
   "name": "Nightmare Spiral",
   "effect": "Ranged hits steal 6% of base damage dealt as Health. Consumable Healing Effectiveness is reduced by 95%."
  },
  "Onyx Pendulum": {
   "name": "Onyx Pendulum",
   "effect": "Dealing firearm damage adds stacks which increase the damage of the stowed firearm by 2.5% for 15s. Stacks 10 times."
  },
  "Pocket Watch": {
   "name": "Pocket Watch",
   "effect": "Increases Stamina Regen by 20 per second and reduces Stamina Cost by 20%."
  },
  "Polished Whetstone": {
   "name": "Polished Whetstone",
   "effect": "When attacking a BLEEDING enemy, Crit Chance is increased by 15% and Crit Damage is increased by 35%."
  },
  "Radioactive Ember": {
   "name": "Radioactive Ember",
   "effect": "Increases RADIATION damage by 15% and converts basic melee weapons from physical to elemental dealing RADIATION damage."
  },
  "Razorwire Necklace": {
   "name": "Razorwire Necklace",
   "effect": "Increase BLEEDING damage dealt by 50%. Ranged and Melee damage dealt to BLEEDING enemies is increased by 15%."
  },
  "Rock of Anguish": {
   "name": "Rock of Anguish",
   "effect": "Gain 10% Movement Speed and 15% Reload Speed for every 25% of Max Health missing."
  },
  "Rusted Amulet": {
   "name": "Rusted Amulet",
   "effect": "Reduces Stamina Cost by 80% but increases Armor Encumbrance by 25."
  },
  "Scavenger's Bauble": {
   "name": "Scavenger's Bauble",
   "effect": "Increases the amount of Scrap picked up by 50%."
  },
  "Shattered Vertebrae": {
   "name": "Shattered Vertebrae",
   "effect": "Increase Ranged damage by 10%. When dealing Non-Critical damage with a firearm, Crit Chance is increased by 2% and Crit damage is increased by 5%. When a Critical Hit occurs, Crit Chance and Crit Chance damage are reset."
  },
  "Soul Anchor": {
   "name": "Soul Anchor",
   "effect": "Increases the duration of summoned creatures by 100% and increases wearer's Ranged and Melee damage by 6.25% (max 25%) per summoned minion."
  },
  "Stalker's Brand": {
   "name": "Stalker's Brand",
   "effect": "Firearm sound is reduced by 25%. When crouched, increases Movement Speed by 20% and reduces enemy Awareness Range by 15%."
  },
  "Storm Amulet": {
   "name": "Storm Amulet",
   "effect": "Increases SHOCK damage by 15%. Weapon Mods that inflict SHOCK damage deal an additional 10%."
  },
  "Talisman of Animosity": {
   "name": "Talisman of Animosity",
   "effect": "Increases Weakspot damage by 30%. Weakspot kills increase all damage by 10% for 10 seconds."
  },
  "Talisman of Perseverance": {
   "name": "Talisman of Perseverance",
   "effect": "Increases earned experience by 1% when slaying an enemy and will last until the wearer dies, unequips the amulet, or rests at a checkpoint. stacking up to 50 times."
  },
  "Terror Margin": {
   "name": "Terror Margin",
   "effect": "Melee hits steal 1.5% of the base damage dealt as Health. For every 25% missing Health, gain an additional 1.5% lifesteal. With full health, gain 20% Melee damage."
  },
  "Twisted Idol": {
   "name": "Twisted Idol",
   "effect": "Increases Armor Effectiveness by 30% and reduces Encumbrance by 15."
  },
  "Vengeance Idol": {
   "name": "Vengeance Idol",
   "effect": "All damage dealt is increased by 30% when the wearer's Health is below 50%. Includes Summons."
  },
  "Vulcan's Detonator": {
   "name": "Vulcan's Detonator",
   "effect": "Increases Explosion damage by 25%. Explosion apply BURNING."
  },
  "White Rose": {
   "name": "White Rose",
   "effect": "Increases all damage dealt by 25% for each unequipped firearm."
  }
 },
 "mods": {
  "Banish": {
   "name": "Banish",
   "type": "Utility (Boss Weapon)",
   "effect": "Repulsor Effect Fires a projectile that banishes enemies into another dimension for 4 seconds. When they return, they'll take 1.25x the damage from the Repulsor's primary fire for 8 seconds. Powerful enemies won't be banished, but will take increased damage from the Repulsor."
  },
  "Beckon": {
   "name": "Beckon",
   "type": "Summon",
   "effect": "Summons a WASTELAND SKULL which shoots projectiles that deal 40 damage per hit. Lasts 60 seconds. (Max 2)"
  },
  "Blink Token": {
   "name": "Blink Token",
   "type": "Utility/Damage",
   "effect": "Teleports the caster forward up to 13 meters and creates an electrical blast that deals 210 SHOCK damage within 3 meters."
  },
  "Blizzard": {
   "name": "Blizzard",
   "type": "Damage",
   "effect": "Cast a storm cloud that rains icicles as it travels forward up to 30 meters. Icicles deal 30 FROST damage each and apply FROSTBITE to enemies within 2 meters."
  },
  "Breath of the Desert": {
   "name": "Breath of the Desert",
   "type": "Damage",
   "effect": "Discharge 7 radioactive projectiles that will seek towards enemies within 20 meters and deal 30 RADIATION damage each."
  },
  "Cold Spear": {
   "name": "Cold Spear",
   "type": "Damage",
   "effect": "Throws an ice spear that deals 50 FROST damage within 3.5 meters and applies 3 stacks of FROSTBITE. Direct hits apply the FROZEN effect."
  },
  "Corrosive Aura": {
   "name": "Corrosive Aura",
   "type": "Utility",
   "effect": "Projects a 5 meter aura that moves with the caster and applies CORRODED stacks over time. Each stack reduces enemy defense by 5%. Max 5 stacks. Lasts 30 seconds."
  },
  "Explosive Shot": {
   "name": "Explosive Shot",
   "type": "Damage",
   "effect": "Fires an explosive round that deals up to 240 damage to enemies within 4 meters."
  },
  "Fan of Knives": {
   "name": "Fan of Knives",
   "type": "Damage",
   "effect": "Throw a fan of 7 knives that deal 20 damage each and apply the BLEEDING effect dealing 200 damage over 20 seconds. Max 2 Charges."
  },
  "Flame Thrower": {
   "name": "Flame Thrower",
   "type": "Damage (Boss Weapon)",
   "effect": "Spitfire Effect Spews flames that will ignite targets with the BURNING effect dealing 100 FIRE damage over 10 seconds."
  },
  "Flicker Cloak": {
   "name": "Flicker Cloak",
   "type": "Utility",
   "effect": "Surrounds the caster with a magical shield absorbing 50% of their Max Health in damage from incoming attacks and prevents getting staggered. Lasts 15 seconds. 10 seconds cooldown."
  },
  "Frozen Mist": {
   "name": "Frozen Mist",
   "type": "Weapon",
   "effect": "Fires a projectile that deals 10 FROST damage, releases a freezing cloud that lasts 10 seconds, and applies FROSTBITE to enemies within 3 meters. Applies 3 FROSTBITE stacks on a direct hit. Players walking through the cloud will take damage and FROSTBITE buildup."
  },
  "Fusion Cannon": {
   "name": "Fusion Cannon",
   "type": "Damage (Boss Weapon)",
   "effect": "Fusion Rifle Effect Fires a large powerful beam that penetrates through enemies dealing 180 for a single charge. Multiple charges increase damage dealt, recoil, and beam thickness per charge. 5 stacks. Passive: Charges increase primary fire rate. Mod power slowly drains after 2 seconds of not dealing damage."
  },
  "Gravity Core": {
   "name": "Gravity Core",
   "type": "Damage (Boss Weapon)",
   "effect": "Particle Accelerator Effect Fires a projectile which deals 50 damage and opens a gravity well for 5 seconds. Once unstable it explode dealing up to 500 damage within 5 meters. Adds 300 damage per enemy and divides total damage among all enemies."
  },
  "Hive Shot": {
   "name": "Hive Shot",
   "type": "Damage (Boss Weapon)",
   "effect": "Hive Cannon Effect Fires a projectile that deals 20 CORROSIVE damage within 2.5 meters releasing an insect cloud that lasts for 12 seconds. Spreads to nearby enemies."
  },
  "Hot Shot": {
   "name": "Hot Shot",
   "type": "Damage",
   "effect": "Ammunition is imbued with flame dealing FIRE damage which is increased by 15%. Shots also have a 100% chance to apply the BURNING effect, dealing 100 FIRE damage over 10 seconds. Lasts 15 seconds."
  },
  "Howler's Immunity": {
   "name": "Howler's Immunity",
   "type": "Utility",
   "effect": "Projects a 20 meter aura that moves with the caster and reduces incoming damage to all allies standing in the aura by 15%. Lasts 30 seconds."
  },
  "Hunter's Mark": {
   "name": "Hunter's Mark",
   "type": "Utility",
   "effect": "Marks all enemies within 35 meters for the caster and their allies. Crit Chance against marked enemies is increased by 10%. Lasts 30 seconds."
  },
  "Incinerator": {
   "name": "Incinerator",
   "type": "Damage (Boss Weapon)",
   "effect": "Alternator Effect Spews 11 fireballs that deal 15 FIRE damage within 2 meters each and ignites enemies with BURNING effect dealing 100 FIRE damage over 10 seconds."
  },
  "Iron Sentinel": {
   "name": "Iron Sentinel",
   "type": "Summon",
   "effect": "Summons a full automatic TURRET that shoots at 5 rounds per second and deals 5 damage per hit. Lasts 30 seconds. (Max 2)"
  },
  "Mantle of Thorns": {
   "name": "Mantle of Thorns",
   "type": "Utility",
   "effect": "Reduces Melee damage taken from enemies by 20%, reflects 120% of Melee damage taken, and reduces stagger on hit. Lasts 60 seconds."
  },
  "Mender's Aura": {
   "name": "Mender's Aura",
   "type": "Utility",
   "effect": "Creates a 2.3 meter healing pool that regenerates 10 Health per second. Lasts 10 seconds."
  },
  "Radioactive Volley": {
   "name": "Radioactive Volley",
   "type": "Damage (Boss Weapon)",
   "effect": "Defiler Effect Fires a volley of 6 Radioactive projectiles that bounce off of the environment and deal 35 RADIATION damage each."
  },
  "Rattle Weed": {
   "name": "Rattle Weed",
   "type": "Summon/Utility",
   "effect": "Shoots a projectile that summons a RATTLE WEED upon impact with 200 Health and draws aggro on enemies within 10 meters. Lasts 10 seconds. Does not affect powerful enemies. (Max 1)"
  },
  "Rift Walker": {
   "name": "Rift Walker",
   "type": "Utility/Summon",
   "effect": "Enter a rift for 2.8 seconds leaving a summoned CLONE behind which draws aggro within 12.5 meters. The caster is invulnerable and their Movement Speed is increased by 30%. Upon exiting, the clone explodes dealing 250 damage within 5.5 meters. Does not affect powerful enemies. 15 second cooldown. (Max 1)."
  },
  "Seed Caller": {
   "name": "Seed Caller",
   "type": "Summon",
   "effect": "Summons a ROOT HOLLOW that deals 50 damage per hit. Lasts 30 seconds. (Max 2)"
  },
  "Seeker": {
   "name": "Seeker",
   "type": "Summons a",
   "effect": "BEETLE that will rush towards enemies and explode dealing 160 CORROSIVE damage within 4 meters. Lasts 30 seconds. (Max 3) Weapon Summons a"
  },
  "Skewer": {
   "name": "Skewer",
   "type": "Damage (Boss Weapon)",
   "effect": "Devastator Effect Fires a large spike that deals 125 damage, 300% additional stagger damage, and applies BLEEDING effect dealing 600 damage over 20 seconds."
  },
  "Song of Swords": {
   "name": "Song of Swords",
   "type": "Utility",
   "effect": "Projects a 25 meter aura that moves with the caster. All allies standing in the aura will have all of their damage dealt increased by 10%. Lasts for 30 seconds."
  },
  "Spore Shot": {
   "name": "Spore Shot",
   "type": "Damage (Boss Weapon)",
   "effect": "Sporebloom Effect Fires an explosive round that deals 25 ROT damage within 3 meters and will leave a deadly gas cloud that slows enemies and lasts for 7 seconds."
  },
  "Static Field Shot": {
   "name": "Static Field Shot",
   "type": "Damage (Boss Weapon)",
   "effect": "Eye of the Storm Effect Fires a projectile that deals 65 SHOCK damage and applies the OVERLOADED effect. Overloaded enemies will trigger an explosion when they get within 4 meters from each other dealing up to 325 SHOCK damage within a 5 meter radius."
  },
  "Storm Caller": {
   "name": "Storm Caller",
   "type": "",
   "effect": ""
  },
  "Swarm": {
   "name": "Swarm",
   "type": "Damage",
   "effect": "Unleash insects that will seek after enemies within 20 meters and repeatedly attack dealing 5 CORROSIVE damage per hit. Lasts 15 seconds"
  },
  "Tentacle Shot": {
   "name": "Tentacle Shot",
   "type": "Summon (Boss Weapon)",
   "effect": "Curse of the Jungle God Effect Launches a projectile which summon a TENTACLE. Tentacles deals 75 SHOCK damage, steals 1.25% of the hero's Max Health per hit and apply the OVERLOADED effect. Lasts 30 seconds. (Max 2)."
  },
  "Undying": {
   "name": "Undying",
   "type": "Utility (Boss Weapon)",
   "effect": "Ruin Effect If charged upon death, the wielder will be revived with 50% Health. They will also take 10% less damage and be immune to Status effects for 5 seconds. 5 minutes cooldown."
  },
  "Unstable Quills": {
   "name": "Unstable Quills",
   "type": "Damage",
   "effect": "Unleash a rapid burst of 12 quills. Cast again to detonate, dealing 15 CORROSIVE damage each within 2.5 meters. Overcharge quills by shooting an enemy with quills attached until they glow, then detonate increasing the damage to 30 CORROSIVE damage each."
  },
  "Vampiric": {
   "name": "Vampiric",
   "type": "Fires",
   "effect": "4 beetles that will fly towards enemies within 10 meters, land on them, and steal 50 health over 5 seconds. Once full, they will fly back and heal the hero. Weapon Fires"
  },
  "Veil of the Black Tear": {
   "name": "Veil of the Black Tear",
   "type": "Utility",
   "effect": "Generates a 5 meter impenetrable energy field. Heroes standing inside the energy field can shoot outward. Lasts 10 seconds."
  },
  "Very Good Boy": {
   "name": "Very Good Boy",
   "type": "Summon",
   "effect": "Summons a VERY GOOD BOY that deals 80 damage per bite. Pet the dog to increase his damage dealt by 5% for 60 seconds. Lasts 60 seconds (Max 1)"
  },
  "Wildfire Shot": {
   "name": "Wildfire Shot",
   "type": "Shoots an arcing fireball that deals",
   "effect": "25 FIRE damage and ignites enemies with the BURNING effect within 2 meters, dealing 300 FIRE damage over 10 seconds. Weapon Shoots an arcing fireball that deals"
  }
 },
 "sets": {
  "Adventurer Set": {
   "set": "Adventurer Set",
   "bonus": "Treasure Hunter",
   "effect": "Increases chance to get materials from destroying breakables. Increases the amount of scrap picked up by 20%",
   "pieces": [
    "+10%",
    "+20%",
    "+35%"
   ]
  },
  "Akari Set": {
   "set": "Akari Set",
   "bonus": "Opportunist",
   "effect": "Perfect Dodging increases Firing, Melee, Reload, and Evade Speed for 20 seconds. Taking direct damage removes the buff. Slightly increases Evade Window.",
   "pieces": [
    "+7.5%",
    "+15%",
    "+30%"
   ]
  },
  "Bandit Set": {
   "set": "Bandit Set",
   "bonus": "Freeloader",
   "effect": "Chance to replace spent bullet on hit. Increases Ammo acquired on pickup by 25%.",
   "pieces": [
    "10%",
    "20%",
    "35%"
   ]
  },
  "Bomber Hat": {
   "set": "Bomber Hat",
   "bonus": "Team Player",
   "effect": "Increases the Range of the Teamwork trait.",
   "pieces": [
    "+10m",
    "+20m",
    "+30m"
   ]
  },
  "Carapace Set": {
   "set": "Carapace Set",
   "bonus": "Harden",
   "effect": "After avoiding damage for 15s, armor hardens 1x per piece granting damage reduction. Damage removes a stack. If all stacks are removed, gain 10% bonus Movement Speed per piece ( 30% Max) for 5s. Increases Total damage from all sources by 5% per piece.",
   "pieces": [
    "+7.5%",
    "+15%",
    "+25%"
   ]
  },
  "Cultist Set": {
   "set": "Cultist Set",
   "bonus": "Blood Pact",
   "effect": "Increases Weapon Mod duration. Mod Power is generated slowly over time.",
   "pieces": [
    "+15%",
    "+30%",
    "+50%"
   ]
  },
  "Drifter Set": {
   "set": "Drifter Set",
   "bonus": "Wanderer",
   "effect": "Sprinting for 1s. Evading, or sliding adds 1 stack of inertia. Inertia stacks increase Ranged and Melee damage. Max 5 Stacks. Lasts 10 seconds. Increases Stamina Regen by 15 per second.",
   "pieces": [
    "+1.5%",
    "+3%",
    "+5%"
   ]
  },
  "Elder Set": {
   "set": "Elder Set",
   "bonus": "Believer",
   "effect": "Dragon Hearts increases the Total damage dealt by all allies standing within 40 meters for 30 seconds. Gives a 25% chance to not consume a Dragon Heart",
   "pieces": [
    "7.5%",
    "15%",
    "30%"
   ]
  },
  "Hunter Set": {
   "set": "Hunter Set",
   "bonus": "Sharpshooter",
   "effect": "Increases total Ranged and Weakspot damage. Reduces Spread of firearms by 20%",
   "pieces": [
    "+5%",
    "+10%",
    "+20%"
   ]
  },
  "Labyrinth Set": {
   "set": "Labyrinth Set",
   "bonus": "Power Surge",
   "effect": "Increase Total Weapon Mod damage. Refunds 10% of Mod Power on use.",
   "pieces": [
    "+15%",
    "+30%",
    "+50%"
   ]
  },
  "Leto's Set": {
   "set": "Leto's Set",
   "bonus": "Juggernaut",
   "effect": "3-Piece: Reduces base incoming damage by 10%. Gain an additional 10% per 10% Max Health missing. Max 5 stacks.",
   "pieces": [
    "-25%",
    "- 1",
    "+10%"
   ]
  },
  "Osseus Set": {
   "set": "Osseus Set",
   "bonus": "Bloodlust",
   "effect": "Subsequent Ranged or Melee hits against the same enemy increases wearer's Total damage dealt to that enemy. Effect degrades over time. Melee Speed and Fire Rate is increased by 5%.",
   "pieces": [
    "+10%",
    "+20%",
    "+35%"
   ]
  },
  "Radiant Set": {
   "set": "Radiant Set",
   "bonus": "Momentum",
   "effect": "Critical hits increase Crit Chance and Crit damage for 3 seconds, stacking up to 10 times. Recoil is reduced by 15%.",
   "pieces": [
    "+0.75%",
    "+1.5%",
    "+3%"
   ]
  },
  "Scavenger Set": {
   "set": "Scavenger Set",
   "bonus": "Salvager",
   "effect": "Ammo, Iron, Scrap pickups increase Total Ranged and Melee damage dealt, and reduce incoming damage. Stacks 10x. Lasts 60s. At or below 50% Health, pickups grant 2 stacks. Taking direct damage removes 5 stacks. Pull Scrap and Iron materials towards the wearer.",
   "pieces": [
    "+0.5%",
    "+1%",
    "+2%"
   ]
  },
  "Scrapper Set": {
   "set": "Scrapper Set",
   "bonus": "Challenger",
   "effect": "Increases Total Damage from all sources dealt by wearer to enemies within 5 meters. Receive 15% less damage from enemies within this range",
   "pieces": [
    "+7.5%",
    "+15%",
    "+30%"
   ]
  },
  "Slayer Set": {
   "set": "Slayer Set",
   "bonus": "Assassin",
   "effect": "Reloading increases the Total damage dealt to the next enemy hit with that weapon. Lasts 10 seconds. Reload speed is increased by 10%",
   "pieces": [
    "+7.5%",
    "+15%",
    "+30%"
   ]
  },
  "Twisted Set": {
   "set": "Twisted Set",
   "bonus": "Regrowth",
   "effect": "At full health, gain a Regrowth stack every 3 seconds which increases Total outgoing Melee and Weapon Mod damage. Stacks 10x. Taking damage removes 5 stacks. Regenerates 0.334 Health per second.",
   "pieces": [
    "+0.75%",
    "+1.5%",
    "+3%"
   ]
  },
  "Void Set": {
   "set": "Void Set",
   "bonus": "Power Transfer",
   "effect": "After 5 seconds, gain a boost that increases Total damage from all sources. Taking damage transfers the boost from Damage to Damage Reduction for 5 seconds. Standing Aim Movement Speed is increased by 25%.",
   "pieces": [
    "+7.5%",
    "+15%",
    "+25%"
   ]
  },
  "Warlord's Set": {
   "set": "Warlord's Set",
   "bonus": "Deathwish",
   "effect": "Dragon Hearts are no longer consumed for healing. They instead increase Ranged and Melee damage, grant lifesteal, and drain 200% health over 30s. Kills heal 5% over 3s.",
   "pieces": [
    "+10%",
    "+25%",
    "+40%"
   ]
  }
 }
};
if (typeof module !== 'undefined') module.exports = RWA_STATS;
