<#
  Generates js/wiki.js: the Fextralife wiki page of every item in js/data.js.
  Each candidate URL is requested and only pages that exist are kept, so the
  page never shows a globe that leads to a 404.

  Usage:  powershell -ExecutionPolicy Bypass -File tools\build-wiki.ps1
#>
$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
$Base = 'https://remnantfromtheashes.wiki.fextralife.com/'

$text = [IO.File]::ReadAllText((Join-Path $Root 'js\data.js'), [Text.Encoding]::UTF8)
$data = ($text -replace '^[^{]*', '' -replace ';\s*if \(typeof[\s\S]*$', '') | ConvertFrom-Json

# 200 -> the slug; redirect -> where it points (if that exists); otherwise $null.
function Test-Page([string]$slug) {
  try {
    $r = Invoke-WebRequest -UseBasicParsing -Uri ($Base + $slug) -TimeoutSec 30 -MaximumRedirection 0 -ErrorAction Stop
    if ($r.StatusCode -eq 200) { return $slug }
  } catch {
    $res = $_.Exception.Response
    if ($res -and [int]$res.StatusCode -ge 300 -and [int]$res.StatusCode -lt 400 -and $res.Headers['Location']) {
      $to = ([string]$res.Headers['Location']) -replace '^https?://[^/]+/', '' -replace '^/', ''
      if ($to -and $to -ne $slug) { return (Test-Page $to) }
    }
  }
  return $null
}

function Get-Candidates([string]$name) {
  $n = $name.Trim() -replace '\s+', ' '
  $title = (Get-Culture).TextInfo.ToTitleCase($n)
  $small = [regex]::Replace($n, '(?<=\s)(Of|The|As|And|A)(?=\s)', { $args[0].Value.ToLower() })
  # The wiki is inconsistent: "Butchers_Flail", "Stone_Of_Balance", "Cold_as_Ice", "Voice_of_The_Tempest".
  $list = @($n, ($n -replace ' Emote$', ''), ($n -replace '^The ', ''), ($n -replace "'", [string][char]0x2019),
    ($n -replace "'", ''), $title, $small, ($n -creplace ' the ', ' The '))
  $list | Select-Object -Unique | ForEach-Object { [Uri]::EscapeUriString(($_ -replace ' ', '_')) -replace "'", '%27' }
}

$items = [ordered]@{}
$missing = @()
$names = $data.items | ForEach-Object { $_.name } | Select-Object -Unique
$i = 0
foreach ($name in $names) {
  $i++
  Write-Progress -Activity 'Checking wiki pages' -Status $name -PercentComplete (100 * $i / $names.Count)
  $found = $null
  foreach ($c in (Get-Candidates $name)) { $found = Test-Page $c; if ($found) { break } }
  if ($found) { $items[$name] = [Uri]::UnescapeDataString($found) } else { $missing += $name }
}

$json = $items | ConvertTo-Json -Compress
$out = "// Generated by tools/build-wiki.ps1 - do not edit by hand.`n" +
  "// Fextralife wiki page (path after remnantfromtheashes.wiki.fextralife.com/) of each item, by item name.`n" +
  "var RWA_WIKI = { items: $json };`n" +
  "if (typeof module !== 'undefined') module.exports = RWA_WIKI;`n"
[IO.File]::WriteAllText((Join-Path $Root 'js\wiki.js'), $out, (New-Object Text.UTF8Encoding($false)))

Write-Host "js/wiki.js: $($items.Count) of $($names.Count) items have a wiki page"
if ($missing.Count) { Write-Host "-- Without a page:"; $missing | ForEach-Object { Write-Host "  $_" } }
